# Taps
tap 'puma/puma'

# Brews
brew 'bat'
brew 'diff-so-fancy'
brew 'emojify'
brew 'elixir'
brew 'flyctl'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'imagemagick'
brew 'mailcatcher', restart_service: true
brew 'neovim'
brew 'nodenv'
brew 'lsd'
brew 'openssl'
brew 'overmind'
brew 'postgresql', restart_service: true
brew 'puma/puma/puma-dev'
brew 'pyenv'
brew 'rbenv'
brew 'redis', restart_service: true
brew 'rustup'
brew 'powerlevel10k'
brew 'stow'
brew 'tmux'
brew 'ripgrep'
brew 'translate-shell'
brew 'tree'
brew 'yarn'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-syntax-highlighting'

# Casks
cask 'font-hack-nerd-font'
cask 'garmin-express'
cask 'iterm2'
cask 'maccy'
cask 'rectangle'
cask 'slack'
cask 'stats'
