# Taps
tap 'heroku/brew'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'puma/puma'

# Brews
brew 'bat'
brew 'diff-so-fancy'
brew 'emojify'
brew 'elixir'
brew 'flyctl'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'gh'
brew 'heroku/brew/heroku'
brew 'imagemagick'
brew 'maccy'
brew 'mailcatcher', restart_service: true
brew 'neovim'
brew 'nodenv'
brew 'lsd'
brew 'openssl'
brew 'overmind'
brew 'postgresql', restart_service: true
brew 'puma/puma/puma-dev'
brew 'pyenv'
brew 'rbenv'
brew 'redis', restart_service: true
brew 'powerlevel10k'
brew 'stow'
brew 'tmux'
brew 'ripgrep'
brew 'translate-shell'
brew 'tree'
brew 'vim'
brew 'yarn'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

# Casks
cask 'discord'
cask 'font-hack-nerd-font'
cask 'garmin-express'
cask 'google-drive'
cask 'insomnia'
cask 'iterm2'
cask 'notion'
cask 'rectangle'
cask 'slack'
cask 'stats'
cask 'whatsapp'
